# Generated by Django 4.0.2 on 2022-02-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('search_url', models.URLField(blank=True, max_length=2000)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_id', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('assignee', models.CharField(blank=True, max_length=500)),
                ('inventors', models.TextField(blank=True)),
                ('priority_date', models.DateField(blank=True, null=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('result_link', models.URLField(blank=True, max_length=500)),
                ('figure_link', models.URLField(blank=True, max_length=500)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='patents.dataset')),
            ],
            options={
                'ordering': ['-publication_date', 'patent_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='patent',
            constraint=models.UniqueConstraint(fields=('dataset', 'patent_id'), name='unique_patent_per_dataset'),
        ),
    ]
