# Generated by Django 4.0.3 on 2022-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['-publication_date', 'patent_id'], name='patent_publication_idx'),
        ),
        migrations.AddIndex(
            model_name='patent',
            index=models.Index(fields=['assignee'], name='patent_assignee_idx'),
        ),
    ]
