# Generated by Django 5.2.10 on 2026-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0002_patent_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pattern',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dataset',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='source_revision',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patent',
            name='application_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patent',
            name='family_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
