# Generated by Django 5.2.10 on 2026-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_collected_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='figure_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='thumbnail_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
