# Generated by Django 5.2.11 on 2026-02-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0004_patent_figures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='imported_at',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='search_url',
        ),
    ]
