# Generated by Django 5.2.12 on 2026-03-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0005_topics_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='assignee_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='patent',
            name='cited_by',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patent',
            name='publication_numbers',
            field=models.TextField(blank=True),
        ),
    ]
