# Generated by Django 5.2.12 on 2026-03-14 12:10

from django.db import migrations, models


def to_memberships(apps, schema_editor):
    """Each patent row of a dataset becomes a membership of one shared patent;
    the same patent in several datasets is kept once."""
    Patent = apps.get_model("patents", "Patent")
    Membership = Patent._meta.get_field("topics").remote_field.through
    first = {}
    duplicates = []
    memberships = []
    for pk, patent_id, topic_id in Patent.objects.order_by("pk").values_list("pk", "patent_id", "dataset_id"):
        kept = first.setdefault(patent_id, pk)
        memberships.append(Membership(patent_id=kept, topic_id=topic_id))
        if kept != pk:
            duplicates.append(pk)
    Membership.objects.bulk_create(memberships, batch_size=1000, ignore_conflicts=True)
    for start in range(0, len(duplicates), 500):
        Patent.objects.filter(pk__in=duplicates[start : start + 500]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("patents", "0006_patent_details"),
    ]

    operations = [
        migrations.RenameModel("Dataset", "Topic"),
        migrations.AddField(
            model_name="patent",
            name="topics",
            field=models.ManyToManyField(related_name="+", to="patents.topic"),
        ),
        migrations.RunPython(to_memberships, migrations.RunPython.noop),
        migrations.RemoveConstraint(model_name="patent", name="unique_patent_per_dataset"),
        migrations.RemoveField(model_name="patent", name="dataset"),
        migrations.AlterField(
            model_name="patent",
            name="topics",
            field=models.ManyToManyField(related_name="patents", to="patents.topic"),
        ),
        migrations.AddConstraint(
            model_name="patent",
            constraint=models.UniqueConstraint(fields=("patent_id",), name="unique_patent_id"),
        ),
    ]
