# Generated by Django 5.2.12 on 2026-03-17 12:06

from django.db import migrations, models

# Keywords of the default topics at the time of this migration.
DEFAULT_KEYWORDS = {
    "drones": ["drone", "uav", "unmanned aerial", "multicopter", "quadcopter"],
    "autonomous-driving": ["autonomous driving", "autonomous vehicle", "self-driving", "driverless"],
    "cybersecurity": ["malware", "intrusion detection", "ransomware", "phishing", "cyber attack", "cyberattack",
                      "cybersecurity"],
}


def default_keywords(apps, schema_editor):
    from patents.keywords import topic_pattern

    Topic = apps.get_model("patents", "Topic")
    for slug, keywords in DEFAULT_KEYWORDS.items():
        Topic.objects.filter(slug=slug).update(keywords=",".join(keywords), pattern=topic_pattern(keywords))


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0007_shared_patents'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('ready', 'ready'), ('queued', 'queued'), ('collecting', 'collecting'), ('failed', 'failed')], default='ready', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pattern',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.RunPython(default_keywords, migrations.RunPython.noop),
    ]
