# Generated by Django 5.2.12 on 2026-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0008_topic_keywords_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='job',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
