# Generated by Django 5.2.12 on 2026-04-07 12:31

from django.db import migrations


def recompute(apps, schema_editor):
    """Patterns are derived from keywords; keywords.plural now also knows
    -y/-ies and -es endings."""
    from patents.keywords import topic_pattern

    Topic = apps.get_model("patents", "Topic")
    for topic in Topic.objects.exclude(keywords=""):
        Topic.objects.filter(pk=topic.pk).update(pattern=topic_pattern(topic.keywords.split(",")))


class Migration(migrations.Migration):

    dependencies = [
        ("patents", "0009_topic_job"),
    ]

    operations = [
        migrations.RunPython(recompute, migrations.RunPython.noop),
    ]
