# Generated by Django 3.0.2 on 2020-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_id', models.CharField(max_length=150, unique=True)),
                ('title', models.TextField()),
                ('assignee', models.TextField()),
                ('inventor_author', models.TextField()),
                ('priority_date', models.TextField()),
                ('filing_creation_date', models.TextField()),
                ('publication_date', models.TextField()),
                ('grant_date', models.TextField()),
                ('result_link', models.TextField()),
                ('representative_figure_link', models.TextField()),
            ],
        ),
    ]
