dev:
	python manage.py runserver 0.0.0.0:8080

superuser:
	python manage.py createsuperuser

package-update:
	pip freeze > requirements.txt

### etc ###
# python manage.py makemigrations
# python manage.py migrate
# python manage.py createsuperuser
# python manage.py runserver